<?php

namespace AppBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchGroup($data)
    {
        $queryBuilder = $this->createQueryBuilder('groupe')
            ->select('groupe')
            ->where('groupe.dateDebutG<=?1')
            ->andWhere('groupe.dateFinG>=?2')
            ->andWhere('groupe.lieuG=?3')
            ->setParameters(array(1 => $data['dateDebutG'], 2 => $data['dateFinG'], 3 => $data['lieuG']));

        return ($queryBuilder->getQuery()->execute());
    }
}
